% Example state matrix: Global timer 1 triggers global timers 2 and 3 (after its onset delay) using the
% 'OnsetTrigger' binary trigger argument. 
% Requires: behavior ports or lickometers with visible LEDs connected to Ch1, Ch2 and Ch3

sma = NewStateMachine;
sma = SetGlobalTimer(sma, 'TimerID', 1, 'Duration', 0.5, 'OnsetDelay', 0,...
                     'Channel', 'PWM1', 'PulseWidthByte', 255, 'PulseOffByte', 0,...
                     'Loop', 0, 'SendGlobalTimerEvents', 1, 'LoopInterval', 0, 'OnsetTrigger', '110'); 
sma = SetGlobalTimer(sma, 'TimerID', 2, 'Duration', 0.5, 'OnsetDelay', 0.1,...
                     'Channel', 'PWM2', 'PulseWidthByte', 255); 
sma = SetGlobalTimer(sma, 'TimerID', 3, 'Duration', 0.5, 'OnsetDelay', 0.2,...
                     'Channel', 'PWM3', 'PulseWidthByte', 255);            
sma = AddState(sma, 'Name', 'TimerTrig', ...
    'Timer', 0,...
    'StateChangeConditions', {'Tup', 'WaitForPoke'},...
    'OutputActions', {'GlobalTimerTrig', 1});
sma = AddState(sma, 'Name', 'WaitForPoke', ...
    'Timer', 0,...
    'StateChangeConditions', {'Port1In', '>exit'},...
    'OutputActions', {});

