% Example state matrix: A global timer ends an infinite loop. It is
% triggered in the first state, but begins measuring its 3-second Duration 
% after a 1.5s onset delay. When the timer begins measuring, it sends byte 2
% to EchoModule1. When the timer's 3 second duration elapses, 
% byte 5 is sent to EchoModule1, and a GlobalTimer1_End event occurs 
% (handled in both cases by exiting the state machine).

sma = NewStateMatrix();
sma = SetGlobalTimer(sma, 'TimerID', 1, 'Duration', 3, 'OnsetDelay', 1.5, 'Channel', 'EchoModule1',...
    'OnMessage', 2, 'OffMessage', 5); 
sma = AddState(sma, 'Name', 'TimerTrig', ...
    'Timer', 0,...
    'StateChangeConditions', {'Tup', 'Port1Lit'},...
    'OutputActions', {'GlobalTimerTrig', 1});
sma = AddState(sma, 'Name', 'Port1Lit', ...
    'Timer', .25,...
    'StateChangeConditions', {'Tup', 'Port3Lit', 'GlobalTimer1_End', 'LastState'},...
    'OutputActions', {'PWM1', 255});
sma = AddState(sma, 'Name', 'Port3Lit', ...
    'Timer', .25,...
    'StateChangeConditions', {'Tup', 'Port1Lit', 'GlobalTimer1_End', 'LastState'},...
    'OutputActions', {'PWM3', 255});
sma = AddState(sma, 'Name', 'LastState', ...
    'Timer', 0.5,...
    'StateChangeConditions', {'Tup', '>exit'},...
    'OutputActions', {'PWM3', 255});
