% Example state matrix: A condition (GlobalTimer1, On), triggered by entry into port 1 during state 1,
% causes the second state (the pause before port 3 light) to be skipped.
% Requires: behavior ports or lickometers with visible LEDs connected to Ch1, Ch2 and Ch3

sma = NewStateMachine;
sma = SetGlobalTimer(sma, 'TimerID', 1, 'Duration', 1.5, 'OnsetDelay', 0, 'Channel', 'PWM1', 'PulseWidthByte', 255); 
sma = SetCondition(sma, 2, 'GlobalTimer1', 1); %Arguments: (sma, ConditionNumber, ConditionChannel, ConditionValue; 1 = on, 0 = off)
sma = AddState(sma, 'Name', 'Port2Light', ...
    'Timer', 1,...
    'StateChangeConditions', {'Tup', 'Port2Off', 'Port1In', 'TriggerGlobalTimer'},...
    'OutputActions', {'PWM2', 255});
sma = AddState(sma, 'Name', 'Port2Off', ...
    'Timer', 1,...
    'StateChangeConditions', {'Tup', 'Port3Light', 'Condition2', 'Port3Light'},...
    'OutputActions', {});
sma = AddState(sma, 'Name', 'Port3Light', ...
    'Timer', 1,...
    'StateChangeConditions', {'Tup', '>exit'},...
    'OutputActions', {'PWM3', 255});

sma = AddState(sma, 'Name', 'TriggerGlobalTimer', ...
    'Timer', 0,...
    'StateChangeConditions', {'Tup', 'Port2Light'},...
    'OutputActions', {'GlobalTimerTrig', 1});