% Example state matrix: 3 global timers in "loop mode" blink port 1-3 LEDs at different rates.
% The timers are triggered in the first state. Next, the state machine goes into a state
% where it waits for two events:
% 1. Port1In momentarily enters a state that stops global timer 3. Port 3 will stop blinking.
% 2. Exits the state machine.
% Requires: behavior ports or lickometers with visible LEDs connected to Ch1, Ch2 and Ch3

sma = NewStateMachine;
sma = SetGlobalTimer(sma, 'TimerID', 1, 'Duration', 0.1, 'OnsetDelay', 1,...
                     'Channel', 'PWM1', 'PulseWidthByte', 255, 'PulseOffByte', 0,...
                     'Loop', 1, 'SendGlobalTimerEvents', 0, 'LoopInterval', 0.1); 
sma = SetGlobalTimer(sma, 'TimerID', 2, 'Duration', 0.2, 'OnsetDelay', 1,...
                     'Channel', 'PWM2', 'PulseWidthByte', 255, 'PulseOffByte', 0,...
                     'Loop', 1, 'SendGlobalTimerEvents', 0, 'LoopInterval', 0.2); 
sma = SetGlobalTimer(sma, 'TimerID', 3, 'Duration', 0.3, 'OnsetDelay', 1,...
                     'Channel', 'PWM3', 'PulseWidthByte', 255, 'PulseOffByte', 0,...
                     'Loop', 1, 'SendGlobalTimerEvents', 0, 'LoopInterval', 0.3); 
sma = AddState(sma, 'Name', 'TimerTrig1', ...
    'Timer', 0,...
    'StateChangeConditions', {'Tup', 'WaitForPoke'},...
    'OutputActions', {'GlobalTimerTrig', '111'}); % Use binary strings to specify multiple timers (integers specify only one)
sma = AddState(sma, 'Name', 'WaitForPoke', ...
    'Timer', 0,...
    'StateChangeConditions', {'Port1In', 'StopGlobalTimer', 'Port2In', '>exit'},...
    'OutputActions', {});
sma = AddState(sma, 'Name', 'StopGlobalTimer', ...
    'Timer', 0,...
    'StateChangeConditions', {'Tup', 'WaitForPoke'},...
    'OutputActions', {'GlobalTimerCancel', 3});

