% Example state matrix: A global timer in "loop mode" blinks port2 LED 5 times before terminating. 
% Setting 'Loop' to 0 disables loop mode (one-shot). 1 = loop until canceled, 2-255 = discrete number of loops
% It is triggered in the first state. Next, the state machine goes into a state
% where it waits for two events:
% 1. Port1In momentarily enters a state that stops the global timer. Port 2 will stop blinking.
% 2. Exits the state machine.
% Requires: behavior ports or lickometers with visible LEDs connected to Ch1, Ch2 and Ch3

sma = NewStateMachine;
sma = SetGlobalTimer(sma, 'TimerID', 1, 'Duration', 0.5, 'OnsetDelay', 0.5,...
                     'Channel', 'PWM2', 'PulseWidthByte', 255, 'PulseOffByte', 0,...
                     'Loop', 5, 'SendGlobalTimerEvents', 1, 'LoopInterval', 0.5); % Loop = 5 for 5 iterations
sma = AddState(sma, 'Name', 'TimerTrig', ...
    'Timer', 0,...
    'StateChangeConditions', {'Tup', 'WaitForPoke'},...
    'OutputActions', {'GlobalTimerTrig', 1});
sma = AddState(sma, 'Name', 'WaitForPoke', ...
    'Timer', 0,...
    'StateChangeConditions', {'Port1In', 'StopGlobalTimer', 'Port2In', '>exit'},...
    'OutputActions', {});
sma = AddState(sma, 'Name', 'StopGlobalTimer', ...
    'Timer', 0,...
    'StateChangeConditions', {'Tup', 'WaitForPoke'},...
    'OutputActions', {'GlobalTimerCancel', 1});

