% Example state matrix: A condition (Port2, In) causes the second state to be skipped

sma = NewStateMachine;
sma = SetCondition(sma, 2, 'Port2', 1); %Arguments: (sma, ConditionNumber, ConditionChannel, ConditionValue; 1 = high/in, 0 = low/out)
sma = AddState(sma, 'Name', 'Port1Light', ...
    'Timer', 1,...
    'StateChangeConditions', {'Tup', 'Port2Light'},...
    'OutputActions', {'PWM1', 255});
sma = AddState(sma, 'Name', 'Port2Light', ...
    'Timer', 1,...
    'StateChangeConditions', {'Tup', 'Port3Light', 'Condition2', 'Port3Light'},...
    'OutputActions', {'PWM2', 255});
sma = AddState(sma, 'Name', 'Port3Light', ...
    'Timer', 1,...
    'StateChangeConditions', {'Tup', 'exit'},...
    'OutputActions', {'PWM3', 255});