% Example state matrix: Drives a BNC line high and sends a soft code, then
% drives the other BNC line high when the governing computer sends a
% response. Measure both BNC lines with an oscilloscope to see the latency.

sma = NewStateMatrix();

sma = AddState(sma, 'Name', 'SendSoftCode1', ...
    'Timer', .001,...
    'StateChangeConditions', {'Tup', 'WaitForResponse'},...
    'OutputActions', {'SoftCode', 1, 'BNCState', 1});
sma = AddState(sma, 'Name', 'WaitForResponse', ...
    'Timer', .001,...
    'StateChangeConditions', {'SoftCode1', 'HandleSoftCode'},...
    'OutputActions', {});
sma = AddState(sma, 'Name', 'HandleSoftCode', ...
    'Timer', .001,...
    'StateChangeConditions', {'Tup', 'exit'},...
    'OutputActions', {'BNCState', 2});

% Set soft code handler to send byte 
BpodSystem.SoftCodeHandlerFunction = 'SoftCodeHandler_LatencyLoop';