% Example state machine: Choose between two ports

sma = NewStateMatrix();

sma = AddState(sma, 'Name', 'WaitForChoice', ...
    'Timer', 1,...
    'StateChangeConditions', {'Port1In', 'LightPort1', 'Port2In', 'LightPort2'},...
    'OutputActions', {});
sma = AddState(sma, 'Name', 'LightPort1', ...
    'Timer', 1,...
    'StateChangeConditions', {'Tup', 'exit'},...
    'OutputActions', {'PWM1', 255});
sma = AddState(sma, 'Name', 'LightPort2', ...
    'Timer', 1,...
    'StateChangeConditions', {'Tup', 'exit'},...
    'OutputActions', {'PWM2', 255});