function SessionData = BpodNotebook(Op, varargin)
global BpodSystem
Op = lower(Op);
switch Op
    case 'init'
        % Initialize BpodSystem.GUIHandles.Notebook structure
        BpodSystem.GUIHandles.Notebook = struct();
        BpodSystem.GUIData.Notebook = struct();
        BpodSystem.GUIData.Notebook.Notes = cell(1);
        BpodSystem.GUIData.Notebook.MarkerCodes = zeros(1);
        % Creation of all uicontrols
        
        % --- FIGURE -------------------------------------
        BpodSystem.ProtocolFigures.Notebook = figure( ...
            'Tag', 'figure1', ...
            'Units', 'characters', ...
            'Position', [179 10 49.8 32.2307692307692], ...
            'Name', 'BpodNotebook', ...
            'MenuBar', 'none', ...
            'NumberTitle', 'off', ...
            'Color', get(0,'DefaultUicontrolBackgroundColor'));
        
        % --- STATIC TEXTS -------------------------------------
        BpodSystem.GUIHandles.Notebook.text1 = uicontrol( ...
            'Parent', BpodSystem.ProtocolFigures.Notebook, ...
            'Tag', 'text1', ...
            'Style', 'text', ...
            'Units', 'characters', ...
            'Position', [5.80000000000001 8.53846153846156 25 2.15384615384615], ...
            'FontSize', 12, ...
            'FontWeight', 'bold', ...
            'String', 'Editing trial#');
        
        % --- PUSHBUTTONS -------------------------------------
        BpodSystem.GUIHandles.Notebook.pushbutton3 = uicontrol( ...
            'Parent', BpodSystem.ProtocolFigures.Notebook, ...
            'Tag', 'pushbutton3', ...
            'Style', 'pushbutton', ...
            'Units', 'characters', ...
            'Position', [10.6 0.846153846153855 4.8 2.53846153846154], ...
            'FontSize', 14, ...
            'String', '<', ...
            'Callback', @pushbutton3_Callback);
        
        BpodSystem.GUIHandles.Notebook.pushbutton4 = uicontrol( ...
            'Parent', BpodSystem.ProtocolFigures.Notebook, ...
            'Tag', 'pushbutton4', ...
            'Style', 'pushbutton', ...
            'Units', 'characters', ...
            'Position', [34.0000000000001 1.00000000000001 4.8 2.53846153846154], ...
            'FontSize', 14, ...
            'String', '>', ...
            'Callback', @pushbutton4_Callback);
        
        BpodSystem.GUIHandles.Notebook.pushbutton5 = uicontrol( ...
            'Parent', BpodSystem.ProtocolFigures.Notebook, ...
            'Tag', 'pushbutton5', ...
            'Style', 'pushbutton', ...
            'Units', 'characters', ...
            'Position', [41.0000000000001 1.00000000000001 7 2.53846153846154], ...
            'FontSize', 14, ...
            'String', '>>', ...
            'Callback', @pushbutton5_Callback);
        
        BpodSystem.GUIHandles.Notebook.pushbutton6 = uicontrol( ...
            'Parent', BpodSystem.ProtocolFigures.Notebook, ...
            'Tag', 'pushbutton6', ...
            'Style', 'pushbutton', ...
            'Units', 'characters', ...
            'Position', [1.4 0.846153846153855 7 2.53846153846154], ...
            'FontSize', 14, ...
            'String', '<<', ...
            'Callback', @pushbutton6_Callback);
        
        % --- CHECKBOXES -------------------------------------
        BpodSystem.GUIHandles.Notebook.checkbox1 = uicontrol( ...
            'Parent', BpodSystem.ProtocolFigures.Notebook, ...
            'Tag', 'checkbox1', ...
            'Style', 'checkbox', ...
            'Units', 'characters', ...
            'Position', [12.6000000000001 6.69230769230771 25.8 1.76923076923077], ...
            'String', 'Mark trial with code:', ...
            'Callback', @checkbox1_Callback);
        
        % --- EDIT TEXTS -------------------------------------
        BpodSystem.GUIHandles.Notebook.edit2 = uicontrol( ...
            'Parent', BpodSystem.ProtocolFigures.Notebook, ...
            'Tag', 'edit2', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', [31.4000000000001 8.76923076923079 10.2 2.46153846153846], ...
            'FontSize', 14, ...
            'BackgroundColor', [1 1 1], ...
            'String', '1', ...
            'Callback', @edit2_Callback);
        
        BpodSystem.GUIHandles.Notebook.edit1 = uicontrol( ...
            'Parent', BpodSystem.ProtocolFigures.Notebook, ...
            'Tag', 'edit1', ...
            'Style', 'edit', ...
            'Units', 'characters', ...
            'Position', [2 12.1538461538462 45.4 18.6153846153846], ...
            'FontSize', 14, ...
            'BackgroundColor', [1 1 1], ...
            'String', '', ...
            'HorizontalAlignment', 'left', ...
            'Max', 100, ...
            'Callback', @edit1_Callback);
        
        % --- POPUP MENU -------------------------------------
        BpodSystem.GUIHandles.Notebook.popupmenu1 = uicontrol( ...
            'Parent', BpodSystem.ProtocolFigures.Notebook, ...
            'Tag', 'popupmenu1', ...
            'Style', 'popupmenu', ...
            'Units', 'characters', ...
            'Position', [11.0000000000001 4.23076923076925 27.4 2.07692307692308], ...
            'FontSize', 12, ...
            'BackgroundColor', [1 1 1], ...
            'String', {'1','2','3','4','5','6','7','8','9','10'}, ...
            'Callback', @popupmenu1_Callback);
        SessionData = 0;
    case 'sync'
        SessionData = varargin{1};
        nTrials = SessionData.nTrials+1;
        nTrialsLogged = length(BpodSystem.GUIData.Notebook.Notes);
        if nTrials > nTrialsLogged
            BpodSystem.GUIData.Notebook.Notes(nTrialsLogged+1:nTrials) = cell(1,nTrials-nTrialsLogged);
            BpodSystem.GUIData.Notebook.MarkerCodes(nTrialsLogged+1:nTrials) = zeros(1,nTrials-nTrialsLogged);
        end
        SessionData.Notes = BpodSystem.GUIData.Notebook.Notes;
        SessionData.MarkerCodes = BpodSystem.GUIData.Notebook.MarkerCodes;
end
end

%% ---------------------------------------------------------------------------
function pushbutton3_Callback(hObject,evendata) %#ok<INUSD>
global BpodSystem
CurrentTrialViewing = str2double(get(BpodSystem.GUIHandles.Notebook.edit2, 'String'));
if CurrentTrialViewing > 1
    CurrentTrialViewing = CurrentTrialViewing - 1;
end
set(BpodSystem.GUIHandles.Notebook.edit1, 'String', BpodSystem.GUIData.Notebook.Notes{CurrentTrialViewing});
set(BpodSystem.GUIHandles.Notebook.edit2, 'String', num2str(CurrentTrialViewing));
set(BpodSystem.GUIHandles.Notebook.checkbox1, 'Value', BpodSystem.GUIData.Notebook.MarkerCodes(CurrentTrialViewing) > 0)
if BpodSystem.GUIData.Notebook.MarkerCodes(CurrentTrialViewing) > 0
    set(BpodSystem.GUIHandles.Notebook.popupmenu1, 'Value', BpodSystem.GUIData.Notebook.MarkerCodes(CurrentTrialViewing))
else
    set(BpodSystem.GUIHandles.Notebook.popupmenu1, 'Value', 1)
end
drawnow;
end

%% ---------------------------------------------------------------------------
function pushbutton4_Callback(hObject,evendata) %#ok<INUSD>
global BpodSystem
CurrentTrialViewing = str2double(get(BpodSystem.GUIHandles.Notebook.edit2, 'String'));
MaxTrials = length(BpodSystem.GUIData.Notebook.Notes);
if CurrentTrialViewing < MaxTrials
    CurrentTrialViewing = CurrentTrialViewing + 1;
end
set(BpodSystem.GUIHandles.Notebook.edit1, 'String', BpodSystem.GUIData.Notebook.Notes{CurrentTrialViewing});
set(BpodSystem.GUIHandles.Notebook.edit2, 'String', num2str(CurrentTrialViewing));
set(BpodSystem.GUIHandles.Notebook.checkbox1, 'Value', BpodSystem.GUIData.Notebook.MarkerCodes(CurrentTrialViewing) > 0)
if BpodSystem.GUIData.Notebook.MarkerCodes(CurrentTrialViewing) > 0
    set(BpodSystem.GUIHandles.Notebook.popupmenu1, 'Value', BpodSystem.GUIData.Notebook.MarkerCodes(CurrentTrialViewing))
else
    set(BpodSystem.GUIHandles.Notebook.popupmenu1, 'Value', 1)
end
drawnow;
end

%% ---------------------------------------------------------------------------
function pushbutton5_Callback(hObject,evendata) %#ok<INUSD>
global BpodSystem
CurrentTrialViewing = length(BpodSystem.GUIData.Notebook.Notes);
set(BpodSystem.GUIHandles.Notebook.edit1, 'String', BpodSystem.GUIData.Notebook.Notes{CurrentTrialViewing});
set(BpodSystem.GUIHandles.Notebook.edit2, 'String', num2str(CurrentTrialViewing));
set(BpodSystem.GUIHandles.Notebook.checkbox1, 'Value', BpodSystem.GUIData.Notebook.MarkerCodes(CurrentTrialViewing) > 0)
if BpodSystem.GUIData.Notebook.MarkerCodes(CurrentTrialViewing) > 0
    set(BpodSystem.GUIHandles.Notebook.popupmenu1, 'Value', BpodSystem.GUIData.Notebook.MarkerCodes(CurrentTrialViewing))
else
    set(BpodSystem.GUIHandles.Notebook.popupmenu1, 'Value', 1)
end
drawnow;
end

%% ---------------------------------------------------------------------------
function pushbutton6_Callback(hObject,evendata) %#ok<INUSD>
global BpodSystem
CurrentTrialViewing = 1;
set(BpodSystem.GUIHandles.Notebook.edit1, 'String', BpodSystem.GUIData.Notebook.Notes{CurrentTrialViewing});
set(BpodSystem.GUIHandles.Notebook.edit2, 'String', num2str(CurrentTrialViewing));
set(BpodSystem.GUIHandles.Notebook.checkbox1, 'Value', BpodSystem.GUIData.Notebook.MarkerCodes(CurrentTrialViewing) > 0)
if BpodSystem.GUIData.Notebook.MarkerCodes(CurrentTrialViewing) > 0
    set(BpodSystem.GUIHandles.Notebook.popupmenu1, 'Value', BpodSystem.GUIData.Notebook.MarkerCodes(CurrentTrialViewing))
else
    set(BpodSystem.GUIHandles.Notebook.popupmenu1, 'Value', 1)
end
drawnow;
end

%% ---------------------------------------------------------------------------
function checkbox1_Callback(hObject,evendata) %#ok<INUSD>
global BpodSystem
CurrentTrialViewing = str2double(get(BpodSystem.GUIHandles.Notebook.edit2, 'String'));
CBval = get(BpodSystem.GUIHandles.Notebook.checkbox1, 'Value');
if CBval == 1
    BpodSystem.GUIData.Notebook.MarkerCodes(CurrentTrialViewing) = get(BpodSystem.GUIHandles.Notebook.popupmenu1, 'Value');
else
    BpodSystem.GUIData.Notebook.MarkerCodes(CurrentTrialViewing) = 0;
end
drawnow;
end

%% ---------------------------------------------------------------------------
function edit2_Callback(hObject,evendata) %#ok<INUSD>
global BpodSystem
MaxTrials = length(BpodSystem.GUIData.Notebook.Notes);
Num = ceil(str2double(get(BpodSystem.GUIHandles.Notebook.edit2, 'String')));
if ~isnan(Num)
    if Num < 1
        msgbox('Invalid trial number.')
        BpodErrorSound
        Num = 1;
    elseif Num > MaxTrials
        msgbox('Invalid trial number.')
        BpodErrorSound
        Num = MaxTrials;
    end
else
    msgbox('Invalid trial number.')
    BpodErrorSound
    Num = MaxTrials;
end
Str = BpodSystem.GUIData.Notebook.Notes{Num};
set(BpodSystem.GUIHandles.Notebook.edit2, 'String', num2str(Num));
set(BpodSystem.GUIHandles.Notebook.edit1, 'String', Str);
drawnow;
end

%% ---------------------------------------------------------------------------
function edit1_Callback(hObject,evendata) %#ok<INUSD>
global BpodSystem
    CurrentTrialViewing = str2double(get(BpodSystem.GUIHandles.Notebook.edit2, 'String'));
    BpodSystem.GUIData.Notebook.Notes{CurrentTrialViewing} = get(BpodSystem.GUIHandles.Notebook.edit1, 'String');
    drawnow;
end

%% ---------------------------------------------------------------------------
function popupmenu1_Callback(hObject,evendata) %#ok<INUSD>
global BpodSystem
CurrentTrialViewing = str2double(get(BpodSystem.GUIHandles.Notebook.edit2, 'String'));
if get(BpodSystem.GUIHandles.Notebook.checkbox1, 'Value')
    BpodSystem.GUIData.Notebook.MarkerCodes(CurrentTrialViewing) = get(BpodSystem.GUIHandles.Notebook.popupmenu1, 'Value');
end
drawnow;
end
